[project]
name = "cca-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-driver>=0.2.9",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
]
